### ISSUE TITLE
"Subtract fee from amount" does not subtract 100 RTM when futures transaction

### ISSUE THREAD

**Issue by sullystuff** [Raptor3um/Raptoreum#150]
When sending a futures transaction with the GUI wallet, using 'subtract fee from amount' will only subtract the standard network fee, and not the 100 RTM futures fee.
![image](https://user-images.githubusercontent.com/63869300/160960247-b76c06a9-74a5-4b3b-9d01-77a19b6f851b.png)

**Comment by npq7721** [comment]
fee rate should reflect total fee include future so it is working as it should

**Comment by npq7721** [comment]
read it wrong so reopen

**Comment by CodeIsTheKey** [comment]
Confirmed that behavior is correct in CLI - this is a Qt only issue.

**Comment by CodeIsTheKey** [comment]
I looked at subtracting the future tx fee from the amount, but realized that it is handled separately from the normal network fees.

Instead of changing the model to track two sets of fees, I have updated the checkbox on the dialog to indicate network fees, and it now shows the networks fees and special transaction fee in the confirmation dialog.
