### ISSUE TITLE
ubuntu 22 depends build failure

### ISSUE THREAD

**Issue by npq7721** [Raptor3um/Raptoreum#176]
This issue tracker is only for technical issues related to Raptoreum Core.

General Raptoreum questions and/or support requests and are best directed to the [Raptoreum Discord](https://discord.com/invite/2T8xG7e).

To report critical security issues, DM the Core or Developer Teams instead of creating Github issues.

### Describe the issue
Depends do not current build on ubuntu 22. Need to be able to build on ubuntu 22.

**Comment by michal-zurkowski** [comment]
Just some more info about the problem of more specifically boost not compiling.

1. It is because some constants (in this case `PTHREAD_STACK_MIN` were changed in `glibc-2.34` and ubuntu uses `glibc-2.35`.

The boost compile can be "fixed" by changing  one macro in `boost/thread/pthread/thread_data.hpp:60`:
```
#if PTHREAD_STACK_MIN > 0
    if (size < PTHREAD_STACK_MIN) size = PTHREAD_STACK_MIN;
#endif
```
into
```
#ifdef PTHREAD_STACK_MIN
    if (size < static_cast<std::size_t>(PTHREAD_STACK_MIN)) size = PTHREAD_STACK_MIN;
#endif
```

This is just that particular part but from a higher version of boost where it was changed already since boost-1.73

2. Default `gcc` compiler on Ubuntu 22.04 is now `gcc-11` which also causes some problems when compiling the boost 1.70 library. I'm a little lost in the boost lib so I cannot provide a simple fix for it :/


Just fixing 1. allows for compilation but requires a change of the compiler to `gcc-10`.
Both of those issues are addressed in `boost 1.73`.
