### ISSUE TITLE
Why can't raptoreum coin handle staking in raptoreum wallet?

### ISSUE THREAD

**Issue by kbuwel** [Raptor3um/Raptoreum#325]
https://www.sullynode.com/#Dashboard 
https://www.inodez.com/dash-user/data/general 
The two links above are rtm node providers. 
But I'm not sure. 
I doubt they will give me proper compensation when I provide my coins as collateral. 
There are many coins that provide staking within a coin wallet. 
However, Raptoreum is a system that rewards rewards only when collateral is deposited with the node 
provider. 
What should I do if the node provider takes my coins and does not reward me? 
Developer, can you trust the above two node providers? 
Coin fraud is happening all over the world. 
It would be nice to support staking coins in a local wallet.

This issue tracker is only for technical issues related to Raptoreum Core.

General Raptoreum questions and/or support requests and are best directed to the [Raptoreum Discord](https://discord.com/invite/2T8xG7e).

To report critical security issues, DM the Core or Developer Teams instead of creating Github issues.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Raptoreum Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Bigpiggy01** [comment]
There is no staking as a consensus mechanism on RTM and there won't be. There is an incentive for collateralized nodes which provide additional security for the chain.

**Comment by michal-zurkowski** [comment]
You can hold all the coins and make a node yourself.
Node collateral that is needed is 1.8M RTM so you will need to have that many coins in your wallet to get benefits (payouts) for them, in addition, you will need to have a machine with public IP which will have to run 24/7 as a node.

What node providers you mentioned give access to, is they pull the smaller amounts of coins from all the users, and make a full node from that, giving all the users proportional rewards, because not everyone has 1.8M chunk of RTM laying around. Also, if you do not want to host the node yourself, but have 1.8M, they can also host it for you, in that case, your coins stay in your wallet, but you redelegate the actual node hosting and maintenance to the node providers which take some % RTM cut of the rewards.
