### ISSUE TITLE
Mac Wallet crashing/freezing

### ISSUE THREAD

**Issue by alexvenom** [Raptor3um/Raptoreum#82]
Downloaded and installed the latest wallet for Mac OS.
Now when I try to open the app, it shows the Raptoreum logo, shows verifying blocks all the way to 100%, then "Done Loading", then the App crashes. No error message at all.
Anyone else having this issue? Any way to debug and understand what is happening?

**Comment by npq7721** [comment]
would u able to look at debug.log in RaptoreumCore folder and upload it?

Also what ur mac os version

**Comment by newdakto** [comment]
> Downloaded and installed the latest wallet for Mac OS. Now when I try to open the app, it shows the Raptoreum logo, shows verifying blocks all the way to 100%, then "Done Loading", then the App crashes. No error message at all. Anyone else having this issue? Any way to debug and understand what is happening?

Like me , but i'm used win 10 ver 2004

**Comment by Bigpiggy01** [comment]
This usually happens if there has been a disk write error for some reason (not waiting for the wallet to shutdown but forcing the process or a power outage are typical) and possibly an upstream error we're investigating. In the mean time a fix is: 
Download: https://github.com/Raptor3um/raptoreum/releases/download/1.2.15.3/bootstrap.zip
- Stop wallet or daemon
- In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
- Unzip bootstrap and copy folder into your data directory
- Start wallet
